# Generated by Django 4.1.7 on 2023-03-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='car',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_come',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обращения клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_ready',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ремонта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='done_work',
            field=models.TextField(blank=True, null=True, verbose_name='Проведенные работы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='client',
            name='need_to_repare',
            field=models.TextField(blank=True, null=True, verbose_name='Жалобы клиента '),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Замечания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя владельца'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phones',
            field=models.TextField(blank=True, null=True, verbose_name='Телефоны для связи'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='client',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Год выпуска ТС'),
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название работы')),
                ('norma', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Норма часы')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.workcategory')),
            ],
        ),
    ]
